export const contracts = [
  {
    id: 1,
    contractName: "Weir Electrical",
    contractNumber: "C20220420-000001",
    company: "Weir",
    contractType: "Project",
    licenses: "200/250",
    startDate: "4-Mar-2021",
    endDate: "3-Oct-2024",
    status: "Active",
  },
  {
    id: 2,
    contractName: "Construction",
    contractNumber: "CN000002",
    company: "Al Nasr Contracting",
    contractType: "Recurring",
    licenses: "99/100",
    startDate: "9-Aug-2020",
    endDate: "5-Feb-2021",
    status: "Active",
  },
  {
    id: 3,
    contractName: "Small Contract",
    contractNumber: "CN000003",
    company: "Jacobs",
    contractType: "Recurring",
    licenses: "20/45",
    startDate: "17-May-2021",
    endDate: "26-Oct-2022",
    status: "Disabled",
  },
  {
    id: 4,
    contractName: "Pixaera Test",
    contractNumber: "CN000004",
    company: "Pixaera",
    contractType: "Trial",
    licenses: "4/5",
    startDate: "6-Oct-2022",
    endDate: "15-Dec-2023",
    status: "Paused",
  },
  {
    id: 5,
    contractName: "Emerge 10 Years",
    contractNumber: "CN000005",
    company: "Emerge Education",
    contractType: "Recurring",
    licenses: "11/15",
    startDate: "27-Jun-2021",
    endDate: "7-May-2022",
    status: "Active",
  },
  {
    id: 6,
    contractName: "Large Aramco",
    contractNumber: "CN000006",
    company: "Aramco",
    contractType: "Recurring",
    licenses: "1/5",
    startDate: "5-Feb-2021",
    endDate: "24-Apr-2021",
    status: "Disabled",
  },
  {
    id: 7,
    contractName: "Temporary Contract",
    contractNumber: "CN000007",
    company: "Temporary",
    contractType: "Project",
    licenses: "10k/11k",
    startDate: "27-Jun-2020",
    endDate: "11-Sep-2020",
    status: "Active",
  },
  {
    id: 8,
    contractName: "Rio Tinto Test",
    contractNumber: "CN000008",
    company: "Rio Tinto",
    contractType: "Trial",
    licenses: "20/20",
    startDate: "26-Nov-2020",
    endDate: "13-May-2021",
    status: "Active",
  },
  {
    id: 9,
    contractName: "Shell Full",
    contractNumber: "CN000009",
    company: "Shell",
    contractType: "Recurring",
    licenses: "3/10",
    startDate: "9-Jul-2020",
    endDate: "12-Oct-2020",
    status: "Disabled",
  },
];
