export const contracts = [
  {
    id: 1,
    contractName: "Weir Electrical",
    contractNumber: "C20220420-000001",
    company: "Weir",
    contractType: "Project",
    licenses: "200/250",
    startDate: "4-Mar-2021",
    endDate: "3-Oct-2024",
    status: "Active",
  },
  {
    id: 2,
    contractName: "Construction",
    contractNumber: "CN000002",
    company: "Al Nasr Contracting",
    contractType: "Recurring",
    licenses: "99/100",
    startDate: "9-Aug-2020",
    endDate: "5-Feb-2021",
    status: "Active",
  },
  {
    id: 3,
    contractName: "Small Contract",
    contractNumber: "CN000003",
    company: "Jacobs",
    contractType: "Recurring",
    licenses: "20/45",
    startDate: "17-May-2021",
    endDate: "26-Oct-2022",
    status: "Disabled",
  },
  {
    id: 4,
    contractName: "Pixaera Test",
    contractNumber: "CN000004",
    company: "Pixaera",
    contractType: "Trial",
    licenses: "4/5",
    startDate: "6-Oct-2022",
    endDate: "15-Dec-2023",
    status: "Paused",
  },
  {
    id: 5,
    contractName: "Emerge 10 Years",
    contractNumber: "CN000005",
    company: "Emerge Education",
    contractType: "Recurring",
    licenses: "11/15",
    startDate: "27-Jun-2021",
    endDate: "7-May-2022",
    status: "Active",
  },
  {
    id: 6,
    contractName: "Large Aramco",
    contractNumber: "CN000006",
    company: "Aramco",
    contractType: "Recurring",
    licenses: "1/5",
    startDate: "5-Feb-2021",
    endDate: "24-Apr-2021",
    status: "Disabled",
  },
  {
    id: 7,
    contractName: "Temporary Contract",
    contractNumber: "CN000007",
    company: "Temporary",
    contractType: "Project",
    licenses: "10k/11k",
    startDate: "27-Jun-2020",
    endDate: "11-Sep-2020",
    status: "Active",
  },
  {
    id: 8,
    contractName: "Rio Tinto Test",
    contractNumber: "CN000008",
    company: "Rio Tinto",
    contractType: "Trial",
    licenses: "20/20",
    startDate: "26-Nov-2020",
    endDate: "13-May-2021",
    status: "Active",
  },
  {
    id: 9,
    contractName: "Shell Full",
    contractNumber: "CN000009",
    company: "Shell",
    contractType: "Recurring",
    licenses: "3/10",
    startDate: "9-Jul-2020",
    endDate: "12-Oct-2020",
    status: "Disabled",
  },
  {
    id: 10,
    contractName: "Test Contract 1",
    contractNumber: "CN000010",
    company: "Company 1",
    contractType: "Project",
    licenses: "100/150",
    startDate: "1-Jan-2022",
    endDate: "31-Dec-2022",
    status: "Active",
  },
  {
    id: 11,
    contractName: "Test Contract 2",
    contractNumber: "CN000011",
    company: "Company 2",
    contractType: "Recurring",
    licenses: "50/60",
    startDate: "5-Feb-2021",
    endDate: "5-Feb-2022",
    status: "Active",
  },
  {
    id: 12,
    contractName: "Test Contract 3",
    contractNumber: "CN000012",
    company: "Company 3",
    contractType: "Trial",
    licenses: "10/20",
    startDate: "1-Mar-2020",
    endDate: "1-Jan-2021",
    status: "Paused",
  },
  {
    id: 13,
    contractName: "Test Contract 4",
    contractNumber: "CN000013",
    company: "Company 4",
    contractType: "Recurring",
    licenses: "200/250",
    startDate: "10-Apr-2021",
    endDate: "10-Apr-2023",
    status: "Disabled",
  },
  {
    id: 14,
    contractName: "Test Contract 5",
    contractNumber: "CN000014",
    company: "Company 5",
    contractType: "Project",
    licenses: "30/50",
    startDate: "7-Jul-2020",
    endDate: "7-Jan-2021",
    status: "Active",
  },
  {
    id: 15,
    contractName: "Test Contract 6",
    contractNumber: "CN000015",
    company: "Company 6",
    contractType: "Trial",
    licenses: "5/15",
    startDate: "8-May-2021",
    endDate: "8-May-2022",
    status: "Paused",
  },
  {
    id: 16,
    contractName: "Test Contract 7",
    contractNumber: "CN000016",
    company: "Company 7",
    contractType: "Recurring",
    licenses: "10/20",
    startDate: "3-Oct-2021",
    endDate: "3-Oct-2023",
    status: "Active",
  },
  {
    id: 17,
    contractName: "Test Contract 8",
    contractNumber: "CN000017",
    company: "Company 8",
    contractType: "Project",
    licenses: "120/130",
    startDate: "4-Jan-2020",
    endDate: "4-Jan-2022",
    status: "Active",
  },
  {
    id: 18,
    contractName: "Test Contract 9",
    contractNumber: "CN000018",
    company: "Company 9",
    contractType: "Recurring",
    licenses: "150/160",
    startDate: "9-Sep-2021",
    endDate: "9-Sep-2023",
    status: "Disabled",
  },
  {
    id: 19,
    contractName: "Test Contract 10",
    contractNumber: "CN000019",
    company: "Company 10",
    contractType: "Trial",
    licenses: "10/20",
    startDate: "1-Nov-2022",
    endDate: "1-Nov-2023",
    status: "Paused",
  },
  {
    id: 20,
    contractName: "Test Contract 11",
    contractNumber: "CN000020",
    company: "Company 11",
    contractType: "Recurring",
    licenses: "20/30",
    startDate: "25-Dec-2020",
    endDate: "25-Dec-2022",
    status: "Active",
  },
];
